name: Sync to Private Repo

on:
  push:
    branches:
      - main # Change this to 'master' if your default branch is master

jobs:
  sync-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Public Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push code to Private Repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.SYNC_TOKEN }}
        with:
          source-directory: '.' 
          destination-github-username: 'sibesh-ML'            # <-- Updated this!
          destination-repository-name: 'thinkbox-web'         
          user-email: 'sibesh1998@gmail.com'           # <-- Make sure to update this too!
          target-branch: 'main'
