name: Sync to Private Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Public Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
          token: ${{ secrets.SYNC_TOKEN }} # <-- We inject the token here instead!

      - name: Force Push to Private Mirror
        run: |
          # Because we injected the token above, Git is already authenticated!
          # We just use the normal URL now.
          git remote add private https://github.com/sibesh-ML/thinkbox-web.git
          
          git push -f private main
